config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new',        as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions/new'
  get 'dashboard/index'
  get 'search', to: 'search#index'

  resources :users
  resources :sessions
  resources :books

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/dpl.rb
require 'rubygems'
require 'mechanize'
require 'pry-remote'

class DPL
  def initialize(user)
    @user = user
    @agent = Mechanize.new { |agent|
      agent.follow_meta_refresh = true
      agent.user_agent_alias = 'Mac Firefox'
    }
  end

  def search(keywords)
    authenticate
    results = []

    @agent.get("https://catalog.denverlibrary.org/search/default.aspx?ctx=1.1033.0.0.6&type=Keyword") do |search_page|
      form = search_page.form_with(:action => 'https://catalog.denverlibrary.org/search/default.aspx')
      form['ctrlSearchBars:searchbarKeyword:textboxTerm'] = keywords
      form.submit(form.buttons.first)
    end

    results_page = @agent.get("https://catalog.denverlibrary.org/search/components/ajaxResults.aspx?page=1&type=Keyword&term=#{keywords}&by=KW&sort=RELEVANCE")

    [2,4,6,8,10].each do |i|
      row = results_page.search("//*[@id=\"items_table\"]/tr[#{i}]")
      secondary_values = row.search('.nsm-brief-secondary-zone .nsm-short-item').map(&:text)

      result = {
        author: row.search('.nsm-brief-primary-author-group .nsm-short-item').text,
        available: secondary_values[1],
        current_holds: secondary_values[2],
        google_preview: row.search('.gbs-preview-link')[0].attributes['href'].value,
        name: row.search('.nsm-brief-action-link .nsm-short-item').text,
        thumbnail_uri: row.search('img.thumbnail')[0].attributes['src'].value
      }
      results << result
    end

    results
  end

  def holds
    load_initial_data unless @holds
    @holds
  end

  def books
    load_initial_data unless @books
    @books
  end

  def name
    load_initial_data unless @name
    @name
  end

  def loans
    load_initial_data unless @loans
    @loans
  end

  private

  def authenticate
    return if @authenticated

    @agent.get('https://catalog.denverlibrary.org/logon.aspx') do |signin_page|
      form = signin_page.form_with(:action => './logon.aspx')
      form.textboxBarcodeUsername  = @user.dpl_username
      form.textboxPassword = @user.dpl_password

      my_page = form.submit(form.buttons.first)
      @authenticated = my_page.uri.to_s.match? /patronaccount/
    end
    raise 'Authentication error' unless @authenticated
  end

  def load_initial_data
    authenticate

    @name = ''
    @loans = []
    @books = []
    @holds = []

    @agent.get('https://catalog.denverlibrary.org/patronaccount/') do |my_page|
      @name = my_page.search('#ctrlBasicInfo_labelPatron').text
      @name = @name.split(', ').reverse.join(' ').split(' ').map(&:capitalize).join(' ')

      loans_page = my_page.links.find { |l| l.text.match(/items out/i)}.click

      loan_rows = loans_page.search('.patrongrid-row, .patrongrid-alternating-row')
      loan_rows.each do |loan|
        type = loan.search('td:nth-child(3) img').first['alt']
        title = loan.search('td:nth-child(5)').text.strip
        due = loan.search('td:nth-child(7)').text.strip
        renewals = loan.search('td:nth-child(8)').text.strip

        @loans << {type: type, title: title, due: due, renewals: renewals}
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
require 'pp'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :isbn, :thumbnail, :author, :summary)
    end
end

app/controllers/dashboard_controller.rb
require 'rubygems'
require 'mechanize'
require 'pry-remote'

DO_IT_LIVE = false

class DashboardController < ApplicationController
  layout 'dashboard'
  before_action :ensure_logged_in

  def index
    if DO_IT_LIVE
      index_real
    else
      index_fake
    end
  end

  def index_real
    dpl = DPL.new(@current_user)

    @netdplapp_props = {
      user: {
        email: @current_user.email,
        name: dpl.name,
      },
      books: dpl.books,
      loans: dpl.loans,
      holds: dpl.holds,
    }
  end

  def index_fake
    @netdplapp_props = {
      user: {
        email: @current_user.email,
        name: 'Some Name',
      },
      books: [],
      loans: [],
      holds: [],
    }
  end


  private

  def logit(label, thing)
    puts "############## #{label} ###############"
    puts thing.class
    if thing.is_a? Mechanize::Page
      puts thing.uri
    else
      puts thing
    end
  end

  def ensure_logged_in
    unless logged_in?
      raise "OH NO"
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  layout :none
  before_action :ensure_logged_in

  def index
    dpl = DPL.new(@current_user)
    render json: dpl.search(params[:keywords])
  end

  private

  def ensure_logged_in
    unless logged_in?
      raise "OH NO"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_index_url, notice: 'Logged in!'
      # redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_params)
    if @user.save
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  private

  def allowed_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :dpl_username,
      :dpl_password
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, id: :book_isbn %>
  </div>

  <div class="field">
    <%= form.label :thumbnail %>
    <%= form.text_field :thumbnail, id: :book_thumbnail %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary, id: :book_summary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Isbn</th>
      <th>Thumbnail</th>
      <th>Author</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.isbn %></td>
        <td><%= book.thumbnail %></td>
        <td><%= book.author %></td>
        <td><%= book.summary %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @book.thumbnail %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @book.summary %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/dashboard/index.html.erb
<h1>Hello World</h1>
<%= react_component("NetDPLApp", props: @netdplapp_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netdpl</title>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <div id="user_header">
      <% if logged_in? %>
        <%= link_to 'Logout', logout_path %>
      <% else %>
        <%= link_to 'Sign Up', signup_path %>
        <%= link_to 'Log In', login_path %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactOnRailsWithWebpacker</title>
  <%= csrf_meta_tags %>
  <%= javascript_pack_tag 'webpack-bundle' %>
</head>

<body>
  <div id="user_header">
    <%= link_to 'Logout', logout_path %>
  </div>

  <%= yield %>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :dpl_username %><br />
    <%= f.text_field :dpl_username %>
  </div>
  <div class="field">
    <%= f.label :dpl_password %><br />
    <%= f.password_field :dpl_password %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to NetDPL</h1>
<p>Woo!</p>

<%= link_to 'Books', books_path %>